apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: mahjong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: victorgf87/all_pon:latest
          env:
            - name: DATABASE_URL
              value: postgres://postgres:mysecretpassword@postgres-service:5432/myapp_production

            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: RAILS_MASTER_KEY
          ports:
            - containerPort: 3000
