replicaCount: 1

image:
  repository: victorgf87/all_pon:latest
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: localhost
      paths: ["/"]
    - host: mahjongstats.ddns.net
      paths: ["/"]
    - host: mahjongstats.com
      paths: ["/"]
  tls:
    - secretName: rails-tls
      hosts:
        - localhost
        - mahjongstats.ddns.net
        - mahjongstats.com

postgresql:
  enabled: true
  auth:
    username: postgresql
    password: postgresql
    database: railsdb

railsSecrets:
  secretKeyBase: your-secret-key-base
